[package]
name = "profinet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

target = ["x86_64-unknown-linux-gnu", "thumb7m-none-eabi"]

[dependencies]
num_enum = { version = "0.7", default-features = false, features = [
    "complex-expressions",
] }
smoltcp = { version = "0.11", features = ["medium-ethernet", "proto-ipv4"] }
byteorder = { version = "1.5", default-features = false }
