[workspace]
members = ["lib", "runtime"]
resolver = "2"

[workspace.dependencies]
smoltcp = { version = "0.11", default-features = false, features = [
    "medium-ethernet",
    "proto-ipv4",
    "socket-tcp",
    "socket-udp",
    "defmt",
] }
