[package]
name = "profinet-rs-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
profinet-rs-lib = { path = "../lib" }
smoltcp.workspace = true
